version: '3.1'

services:
    db:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: db_password
    renterhood:
        depends_on:
            - db
        build: .
        ports:
            - "8080:80"
        volumes:
            - .:/app
            - /var/www/vendor
        links:
            - db
